### ISSUE TITLE
pfile_create does not have a working minimal example

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Marvin182/pfile-utilities#1]
```
I tried to find out how to create pfiles with `pfile_create`.

I tried:

```bash
$ pfile_create -i - -f 3 -l 1 -o output.pfile
1 2 3 4 5
6 7 8 9 10
```

but this gave me:

```bash
ERROR: Sentence numbers must be in sequence. Current sent = 0, next sent found 
= 1
```

Could you please send me a working minimal example how to create pfiles with 
pfile_create?
```

Original issue reported on code.google.com by `themoose...@googlemail.com` on 26 Jun 2014 at 2:29

**Comment by Marvin182** [comment]
The updated README links a blog article by Martin with some basic explanations and a minimal working examples.
https://martin-thoma.com/what-are-pfiles/

Btw. how are you and why did you check this?
